sonar.projectKey=mtvru_go-project-244
sonar.organization=mtvru

sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,cmd/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
